version: '2'

services:
  ksi-dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ksi-dashboard
    image: fi0ksi/ksi-dashboard
    volumes:
      - ./build:/myapp/build
      - ./config.py:/myapp/config.py:ro
    # ports:
      # - "127.0.0.1:8080:8080"
    entrypoint: /bin/bash
    command: /myapp/docker/build_in_docker.sh
